"""Auto-generated from BMF-Schreiben 2023-2026 (bundesfinanzministerium.de)."""

BMF_AUSLAND_BY_YEAR = {
    2023: {
        "Afghanistan": (30, 20),
        "Albanien": (27, 18),
        "Algerien": (47, 32),
        "Andorra": (41, 28),
        "Angola": (52, 35),
        "Argentinien": (35, 24),
        "Armenien": (24, 16),
        "Aserbaidschan": (44, 29),
        "Australien – Canberra": (51, 34),
        "Australien – Sydney": (68, 45),
        "Australien – im Übrigen": (51, 34),
        "Bahrain": (48, 32),
        "Bangladesch": (50, 33),
        "Barbados": (52, 35),
        "Belgien": (59, 40),
        "Benin": (52, 35),
        "Bolivien": (46, 31),
        "Bosnien und Herzegowina": (23, 16),
        "Botsuana": (46, 31),
        "Brasilien – Brasilia": (57, 38),
        "Brasilien – Rio de Janeiro": (57, 38),
        "Brasilien – Sao Paulo": (53, 36),
        "Brasilien – im Übrigen": (51, 34),
        "Brunei": (52, 35),
        "Bulgarien": (22, 15),
        "Burkina Faso": (38, 25),
        "Burundi": (36, 24),
        "Chile": (44, 29),
        "China – Chengdu": (41, 28),
        "China – Hongkong": (74, 49),
        "China – Kanton": (36, 24),
        "China – Peking": (30, 20),
        "China – Shanghai": (58, 39),
        "China – im Übrigen": (48, 32),
        "Costa Rica": (47, 32),
        "Dominikanische Republik": (45, 30),
        "Dschibuti": (65, 44),
        "Dänemark": (75, 50),
        "Ecuador": (27, 18),
        "El Salvador": (65, 44),
        "Eritrea": (50, 33),
        "Estland": (29, 20),
        "Fidschi": (34, 23),
        "Finnland": (50, 33),
        "Frankreich – Paris": (58, 39),
        "Frankreich – im Übrigen": (53, 36),
        "Gabun": (52, 35),
        "Gambia": (40, 27),
        "Georgien": (35, 24),
        "Ghana": (46, 31),
        "Griechenland – Athen": (40, 27),
        "Griechenland – im Übrigen": (36, 24),
        "Großbritannien und Nordirland – London": (66, 44),
        "Großbritannien und Nordirland – im Übrigen": (52, 35),
        "Guatemala": (34, 23),
        "Guinea": (46, 31),
        "Guinea-Bissau": (32, 21),
        "Haiti": (58, 39),
        "Honduras": (57, 38),
        "Indien – Bangalore": (42, 28),
        "Indien – Chennai": (32, 21),
        "Indien – Kalkutta": (35, 24),
        "Indien – Mumbai": (50, 33),
        "Indien – Neu Delhi": (38, 25),
        "Indien – im Übrigen": (32, 21),
        "Indonesien": (36, 24),
        "Iran": (33, 22),
        "Irland": (58, 39),
        "Island": (62, 41),
        "Israel": (66, 44),
        "Italien – Mailand": (45, 30),
        "Italien – Rom": (40, 27),
        "Italien – im Übrigen": (40, 27),
        "Jamaika": (57, 38),
        "Japan – Tokio": (66, 44),
        "Japan – im Übrigen": (52, 35),
        "Jemen": (24, 16),
        "Jordanien": (57, 38),
        "Kambodscha": (38, 25),
        "Kamerun": (50, 33),
        "Kanada – Ottawa": (47, 32),
        "Kanada – Toronto": (51, 34),
        "Kanada – Vancouver": (50, 33),
        "Kanada – im Übrigen": (47, 32),
        "Kap Verde": (30, 20),
        "Kasachstan": (45, 30),
        "Katar": (56, 37),
        "Kenia": (51, 34),
        "Kirgisistan": (27, 18),
        "Kolumbien": (46, 31),
        "Kongo, Demokratische Republik": (70, 47),
        "Kongo, Republik": (62, 41),
        "Korea, Demokratische": (28, 19),
        "Korea, Republik": (48, 32),
        "Kosovo": (24, 16),
        "Kroatien": (35, 24),
        "Kuba": (46, 31),
        "Kuwait": (56, 37),
        "Laos": (33, 22),
        "Lesotho": (28, 19),
        "Lettland": (35, 24),
        "Libanon": (59, 40),
        "Libyen": (63, 42),
        "Liechtenstein": (56, 37),
        "Litauen": (26, 17),
        "Luxemburg": (63, 42),
        "Madagaskar": (34, 23),
        "Malawi": (41, 28),
        "Malaysia": (36, 24),
        "Malediven": (52, 35),
        "Mali": (38, 25),
        "Malta": (46, 31),
        "Marokko": (42, 28),
        "Marshall Inseln": (63, 42),
        "Mauretanien": (35, 24),
        "Mauritius": (54, 36),
        "Mexiko": (48, 32),
        "Moldau, Republik": (26, 17),
        "Monaco": (52, 35),
        "Mongolei": (27, 18),
        "Montenegro": (32, 21),
        "Mosambik": (38, 25),
        "Myanmar": (35, 24),
        "Namibia": (30, 20),
        "Nepal": (36, 24),
        "Neuseeland": (56, 37),
        "Nicaragua": (46, 31),
        "Niederlande": (47, 32),
        "Niger": (42, 28),
        "Nigeria": (46, 31),
        "Nordmazedonien": (27, 18),
        "Norwegen": (80, 53),
        "Oman": (64, 43),
        "Pakistan – Islamabad": (23, 16),
        "Pakistan – im Übrigen": (34, 23),
        "Palau": (51, 34),
        "Panama": (41, 28),
        "Papua-Neuguinea": (59, 40),
        "Paraguay": (38, 25),
        "Peru": (34, 23),
        "Philippinen": (33, 22),
        "Polen – Breslau": (33, 22),
        "Polen – Danzig": (30, 20),
        "Polen – Krakau": (27, 18),
        "Polen – Warschau": (29, 20),
        "Polen – im Übrigen": (29, 20),
        "Portugal": (32, 21),
        "Ruanda": (44, 29),
        "Rumänien – Bukarest": (32, 21),
        "Rumänien – im Übrigen": (27, 18),
        "Russische Föderation – Jekaterinburg": (28, 19),
        "Russische Föderation – Moskau": (30, 20),
        "Russische Föderation – St. Petersburg": (26, 17),
        "Russische Föderation – im Übrigen": (24, 16),
        "Sambia": (38, 25),
        "Samoa": (39, 26),
        "San Marino": (34, 23),
        "Saudi-Arabien – Djidda": (57, 38),
        "Saudi-Arabien – Riad": (56, 37),
        "Saudi-Arabien – im Übrigen": (56, 37),
        "Schweden": (66, 44),
        "Schweiz – Genf": (66, 44),
        "Schweiz – im Übrigen": (64, 43),
        "Senegal": (42, 28),
        "Serbien": (27, 18),
        "Sierra Leone": (48, 32),
        "Simbabwe": (45, 30),
        "Singapur": (54, 36),
        "Slowakische Republik": (33, 22),
        "Slowenien": (38, 25),
        "Spanien – Barcelona": (34, 23),
        "Spanien – Kanarische Inseln": (40, 27),
        "Spanien – Madrid": (40, 27),
        "Spanien – Palma de Mallorca": (35, 24),
        "Spanien – im Übrigen": (34, 23),
        "Sri Lanka": (42, 28),
        "Sudan": (33, 22),
        "Syrien": (38, 25),
        "Südafrika – Johannesburg": (36, 24),
        "Südafrika – Kapstadt": (33, 22),
        "Südafrika – im Übrigen": (29, 20),
        "Südsudan": (34, 23),
        "Tadschikistan": (27, 18),
        "Taiwan": (46, 31),
        "Tansania": (44, 29),
        "Thailand": (38, 25),
        "Togo": (39, 26),
        "Tonga": (39, 26),
        "Trinidad und Tobago": (45, 30),
        "Tschad": (64, 43),
        "Tschechische Republik": (32, 21),
        "Tunesien": (40, 27),
        "Turkmenistan": (33, 22),
        "Türkei – Istanbul": (26, 17),
        "Türkei – Izmir": (29, 20),
        "Türkei – im Übrigen": (17, 12),
        "Uganda": (41, 28),
        "Ukraine": (26, 17),
        "Ungarn": (32, 21),
        "Uruguay": (48, 32),
        "Usbekistan": (34, 23),
        "Vatikanstaat": (52, 35),
        "Venezuela": (45, 30),
        "Vereinigte Arabische Emirate": (65, 44),
        "Vereinigte Staaten von Amerika (USA) – Atlanta": (77, 52),
        "Vereinigte Staaten von Amerika (USA) – Boston": (63, 42),
        "Vereinigte Staaten von Amerika (USA) – Chicago": (65, 44),
        "Vereinigte Staaten von Amerika (USA) – Houston": (62, 41),
        "Vereinigte Staaten von Amerika (USA) – Los Angeles": (64, 43),
        "Vereinigte Staaten von Amerika (USA) – Miami": (65, 44),
        "Vereinigte Staaten von Amerika (USA) – New York City": (66, 44),
        "Vereinigte Staaten von Amerika (USA) – San Francisco": (59, 40),
        "Vereinigte Staaten von Amerika (USA) – Washington, D. C.": (66, 44),
        "Vereinigte Staaten von Amerika (USA) – im Übrigen": (59, 40),
        "Vietnam": (41, 28),
        "Weißrussland": (20, 13),
        "Zentralafrikanische Republik": (46, 31),
        "Zypern": (42, 28),
        "Ägypten": (50, 33),
        "Äquatorialguinea": (36, 24),
        "Äthiopien": (39, 26),
        "Österreich": (40, 27),
    },
    2024: {
        "Afghanistan": (30, 20),
        "Albanien": (27, 18),
        "Algerien": (47, 32),
        "Andorra": (41, 28),
        "Angola": (52, 35),
        "Argentinien": (35, 24),
        "Armenien": (24, 16),
        "Aserbaidschan": (44, 29),
        "Australien – Canberra": (74, 49),
        "Australien – Sydney": (57, 38),
        "Australien – im Übrigen": (57, 38),
        "Bahrain": (48, 32),
        "Bangladesch": (50, 33),
        "Barbados": (54, 36),
        "Belgien": (59, 40),
        "Benin": (52, 35),
        "Bolivien": (46, 31),
        "Bosnien und Herzegowina": (23, 16),
        "Botsuana": (46, 31),
        "Brasilien – Brasilia": (51, 34),
        "Brasilien – Rio de Janeiro": (69, 46),
        "Brasilien – Sao Paulo": (46, 31),
        "Brasilien – im Übrigen": (46, 31),
        "Brunei": (52, 35),
        "Bulgarien": (22, 15),
        "Burkina Faso": (38, 25),
        "Burundi": (36, 24),
        "Chile": (44, 29),
        "China – Chengdu": (41, 28),
        "China – Hongkong": (71, 48),
        "China – Kanton": (36, 24),
        "China – Peking": (30, 20),
        "China – Shanghai": (58, 39),
        "China – im Übrigen": (48, 32),
        "Costa Rica": (47, 32),
        "Dominikanische Republik": (50, 33),
        "Dschibuti": (77, 52),
        "Dänemark": (75, 50),
        "Ecuador": (27, 18),
        "El Salvador": (65, 44),
        "Eritrea": (50, 33),
        "Estland": (29, 20),
        "Fidschi": (32, 21),
        "Finnland": (54, 36),
        "Frankreich – Paris": (58, 39),
        "Frankreich – im Übrigen": (53, 36),
        "Gabun": (52, 35),
        "Gambia": (40, 27),
        "Georgien": (45, 30),
        "Ghana": (46, 31),
        "Griechenland – Athen": (40, 27),
        "Griechenland – im Übrigen": (36, 24),
        "Großbritannien und Nordirland – London": (66, 44),
        "Großbritannien und Nordirland – im Übrigen": (52, 35),
        "Guatemala": (34, 23),
        "Guinea": (59, 40),
        "Guinea-Bissau": (32, 21),
        "Haiti": (58, 39),
        "Honduras": (57, 38),
        "Indien – Chennai": (32, 21),
        "Indien – Kalkutta": (35, 24),
        "Indien – Mumbai": (50, 33),
        "Indien – Neu Delhi": (38, 25),
        "Indien – im Übrigen": (32, 21),
        "Indonesien": (36, 24),
        "Iran": (33, 22),
        "Irland": (58, 39),
        "Island": (62, 41),
        "Israel": (66, 44),
        "Italien – Mailand": (42, 28),
        "Italien – Rom": (48, 32),
        "Italien – im Übrigen": (42, 28),
        "Jamaika": (39, 26),
        "Japan – Tokio": (50, 33),
        "Japan – im Übrigen": (52, 35),
        "Jemen": (24, 16),
        "Jordanien": (57, 38),
        "Kambodscha": (38, 25),
        "Kamerun": (56, 37),
        "Kanada – Ottawa": (62, 41),
        "Kanada – Toronto": (54, 36),
        "Kanada – Vancouver": (63, 42),
        "Kanada – im Übrigen": (54, 36),
        "Kap Verde": (38, 25),
        "Kasachstan": (45, 30),
        "Katar": (56, 37),
        "Kenia": (51, 34),
        "Kirgisistan": (27, 18),
        "Kolumbien": (46, 31),
        "Kongo, Demokratische Republik": (70, 47),
        "Kongo, Republik": (62, 41),
        "Korea, Demokratische": (28, 19),
        "Korea, Republik": (48, 32),
        "Kosovo": (24, 16),
        "Kroatien": (35, 24),
        "Kuba": (51, 34),
        "Kuwait": (56, 37),
        "Laos": (35, 24),
        "Lesotho": (28, 19),
        "Lettland": (35, 24),
        "Libanon": (69, 46),
        "Libyen": (63, 42),
        "Liechtenstein": (56, 37),
        "Litauen": (26, 17),
        "Luxemburg": (63, 42),
        "Madagaskar": (33, 22),
        "Malawi": (41, 28),
        "Malaysia": (36, 24),
        "Malediven": (52, 35),
        "Mali": (38, 25),
        "Malta": (46, 31),
        "Marokko": (41, 28),
        "Marshall Inseln": (63, 42),
        "Mauretanien": (35, 24),
        "Mauritius": (44, 29),
        "Mexiko": (48, 32),
        "Moldau, Republik": (26, 17),
        "Monaco": (52, 35),
        "Mongolei": (23, 16),
        "Montenegro": (32, 21),
        "Mosambik": (51, 34),
        "Myanmar": (35, 24),
        "Namibia": (30, 20),
        "Nepal": (36, 24),
        "Neuseeland": (58, 39),
        "Nicaragua": (46, 31),
        "Niederlande": (47, 32),
        "Niger": (42, 28),
        "Nigeria": (46, 31),
        "Nordmazedonien": (27, 18),
        "Norwegen": (75, 50),
        "Oman": (64, 43),
        "Pakistan – Islamabad": (23, 16),
        "Pakistan – im Übrigen": (34, 23),
        "Palau": (51, 34),
        "Panama": (41, 28),
        "Papua-Neuguinea": (59, 40),
        "Paraguay": (39, 26),
        "Peru": (34, 23),
        "Philippinen": (41, 28),
        "Polen – Breslau": (33, 22),
        "Polen – Danzig": (30, 20),
        "Polen – Krakau": (27, 18),
        "Polen – Warschau": (29, 20),
        "Polen – im Übrigen": (29, 20),
        "Portugal": (32, 21),
        "Ruanda": (44, 29),
        "Rumänien – Bukarest": (32, 21),
        "Rumänien – im Übrigen": (27, 18),
        "Russische Föderation – Jekaterinburg": (28, 19),
        "Russische Föderation – Moskau": (30, 20),
        "Russische Föderation – St. Petersburg": (26, 17),
        "Russische Föderation – im Übrigen": (24, 16),
        "Sambia": (38, 25),
        "Samoa": (39, 26),
        "San Marino": (34, 23),
        "Saudi-Arabien – Djidda": (57, 38),
        "Saudi-Arabien – Riad": (56, 37),
        "Saudi-Arabien – im Übrigen": (56, 37),
        "Schweden": (66, 44),
        "Schweiz – Genf": (66, 44),
        "Schweiz – im Übrigen": (64, 43),
        "Senegal": (42, 28),
        "Serbien": (27, 18),
        "Sierra Leone": (57, 38),
        "Simbabwe": (45, 30),
        "Singapur": (54, 36),
        "Slowakische Republik": (33, 22),
        "Slowenien": (38, 25),
        "Spanien – Barcelona": (34, 23),
        "Spanien – Kanarische Inseln": (36, 24),
        "Spanien – Madrid": (42, 28),
        "Spanien – Palma de Mallorca": (44, 29),
        "Spanien – im Übrigen": (34, 23),
        "Sri Lanka": (36, 24),
        "Sudan": (33, 22),
        "Syrien": (38, 25),
        "Südafrika – Johannesburg": (36, 24),
        "Südafrika – Kapstadt": (33, 22),
        "Südafrika – im Übrigen": (29, 20),
        "Südsudan": (51, 34),
        "Tadschikistan": (27, 18),
        "Taiwan": (46, 31),
        "Tansania": (44, 29),
        "Thailand": (38, 25),
        "Togo": (39, 26),
        "Tonga": (39, 26),
        "Trinidad und Tobago": (66, 44),
        "Tschad": (42, 28),
        "Tschechische Republik": (32, 21),
        "Tunesien": (40, 27),
        "Turkmenistan": (33, 22),
        "Türkei – Istanbul": (26, 17),
        "Türkei – Izmir": (29, 20),
        "Türkei – im Übrigen": (17, 12),
        "Uganda": (41, 28),
        "Ukraine": (26, 17),
        "Ungarn": (32, 21),
        "Uruguay": (48, 32),
        "Usbekistan": (34, 23),
        "Vatikanstaat": (48, 32),
        "Venezuela": (45, 30),
        "Vereinigte Arabische Emirate": (65, 44),
        "Vereinigte Staaten von Amerika (USA) – Atlanta": (77, 52),
        "Vereinigte Staaten von Amerika (USA) – Boston": (63, 42),
        "Vereinigte Staaten von Amerika (USA) – Chicago": (65, 44),
        "Vereinigte Staaten von Amerika (USA) – Houston": (62, 41),
        "Vereinigte Staaten von Amerika (USA) – Los Angeles": (64, 43),
        "Vereinigte Staaten von Amerika (USA) – Miami": (65, 44),
        "Vereinigte Staaten von Amerika (USA) – New York City": (66, 44),
        "Vereinigte Staaten von Amerika (USA) – San Francisco": (59, 40),
        "Vereinigte Staaten von Amerika (USA) – Washington, D. C.": (66, 44),
        "Vereinigte Staaten von Amerika (USA) – im Übrigen": (59, 40),
        "Vietnam": (41, 28),
        "Weißrussland": (20, 13),
        "Zentralafrikanische Republik": (53, 36),
        "Zypern": (42, 28),
        "Ägypten": (50, 33),
        "Äquatorialguinea": (42, 28),
        "Äthiopien": (39, 26),
        "Österreich": (50, 33),
    },
    2025: {
        "Afghanistan": (30, 20),
        "Albanien": (27, 18),
        "Algerien": (47, 32),
        "Andorra": (41, 28),
        "Angola": (40, 27),
        "Argentinien": (35, 24),
        "Armenien": (29, 20),
        "Aserbaidschan": (44, 29),
        "Australien – Canberra": (74, 49),
        "Australien – Sydney": (57, 38),
        "Australien – im Übrigen": (57, 38),
        "Bahrain": (48, 32),
        "Bangladesch": (46, 31),
        "Barbados": (54, 36),
        "Belgien": (59, 40),
        "Benin": (40, 27),
        "Bhutan": (27, 18),
        "Bolivien": (46, 31),
        "Bosnien und Herzegowina": (23, 16),
        "Botsuana": (46, 31),
        "Brasilien – Brasilia": (51, 34),
        "Brasilien – Rio de Janeiro": (69, 46),
        "Brasilien – Sao Paulo": (46, 31),
        "Brasilien – im Übrigen": (46, 31),
        "Brunei": (45, 30),
        "Bulgarien": (22, 15),
        "Burkina Faso": (38, 25),
        "Burundi": (36, 24),
        "Chile": (44, 29),
        "China – Chengdu": (41, 28),
        "China – Hongkong": (71, 48),
        "China – Kanton": (36, 24),
        "China – Peking": (30, 20),
        "China – Shanghai": (58, 39),
        "China – im Übrigen": (48, 32),
        "Costa Rica": (60, 40),
        "Dominikanische Republik": (50, 33),
        "Dschibuti": (77, 52),
        "Dänemark": (75, 50),
        "Ecuador": (27, 18),
        "El Salvador": (65, 44),
        "Eritrea": (46, 31),
        "Estland": (29, 20),
        "Fidschi": (32, 21),
        "Finnland": (54, 36),
        "Frankreich – Paris": (58, 39),
        "Frankreich – im Übrigen": (53, 36),
        "Gabun": (64, 43),
        "Gambia": (40, 27),
        "Georgien": (45, 30),
        "Ghana": (46, 31),
        "Griechenland – Athen": (40, 27),
        "Griechenland – im Übrigen": (36, 24),
        "Großbritannien und Nordirland – London": (66, 44),
        "Großbritannien und Nordirland – im Übrigen": (52, 35),
        "Guatemala": (46, 31),
        "Guinea": (59, 40),
        "Guinea-Bissau": (32, 21),
        "Haiti": (58, 39),
        "Honduras": (57, 38),
        "Indien – Bangalore": (42, 28),
        "Indien – Chennai": (22, 15),
        "Indien – Kalkutta": (32, 21),
        "Indien – Mumbai": (53, 36),
        "Indien – Neu Delhi": (46, 31),
        "Indien – im Übrigen": (22, 15),
        "Indonesien": (45, 30),
        "Iran": (33, 22),
        "Irland": (58, 39),
        "Island": (62, 41),
        "Israel": (66, 44),
        "Italien – Mailand": (42, 28),
        "Italien – Rom": (48, 32),
        "Italien – im Übrigen": (42, 28),
        "Jamaika": (39, 26),
        "Japan – Osaka": (33, 22),
        "Japan – Tokio": (50, 33),
        "Japan – im Übrigen": (33, 22),
        "Jemen": (24, 16),
        "Jordanien": (57, 38),
        "Kambodscha": (42, 28),
        "Kamerun": (56, 37),
        "Kanada – Ottawa": (62, 41),
        "Kanada – Toronto": (54, 36),
        "Kanada – Vancouver": (63, 42),
        "Kanada – im Übrigen": (54, 36),
        "Kap Verde": (38, 25),
        "Kasachstan": (33, 22),
        "Katar": (56, 37),
        "Kenia": (51, 34),
        "Kirgisistan": (27, 18),
        "Kolumbien": (34, 23),
        "Kongo, Demokratische Republik": (65, 44),
        "Kongo, Republik": (62, 41),
        "Korea, Demokratische": (28, 19),
        "Korea, Republik": (48, 32),
        "Kosovo": (24, 16),
        "Kroatien": (46, 31),
        "Kuba": (51, 34),
        "Kuwait": (56, 37),
        "Laos": (35, 24),
        "Lesotho": (28, 19),
        "Lettland": (35, 24),
        "Libanon": (69, 46),
        "Liberia": (65, 44),
        "Libyen": (63, 42),
        "Liechtenstein": (56, 37),
        "Litauen": (26, 17),
        "Luxemburg": (63, 42),
        "Madagaskar": (33, 22),
        "Malawi": (41, 28),
        "Malaysia": (36, 24),
        "Malediven": (70, 47),
        "Mali": (38, 25),
        "Malta": (46, 31),
        "Marokko": (41, 28),
        "Marshall Inseln": (63, 42),
        "Mauretanien": (35, 24),
        "Mauritius": (44, 29),
        "Mexiko": (48, 32),
        "Moldau, Republik": (26, 17),
        "Monaco": (52, 35),
        "Mongolei": (23, 16),
        "Montenegro": (32, 21),
        "Mosambik": (51, 34),
        "Myanmar": (23, 16),
        "Namibia": (30, 20),
        "Nepal": (36, 24),
        "Neuseeland": (58, 39),
        "Nicaragua": (46, 31),
        "Niederlande": (47, 32),
        "Niger": (42, 28),
        "Nigeria": (46, 31),
        "Nordmazedonien": (27, 18),
        "Norwegen": (75, 50),
        "Oman": (64, 43),
        "Pakistan – Islamabad": (23, 16),
        "Pakistan – im Übrigen": (34, 23),
        "Palau": (51, 34),
        "Panama": (41, 28),
        "Papua-Neuguinea": (59, 40),
        "Paraguay": (39, 26),
        "Peru": (34, 23),
        "Philippinen": (41, 28),
        "Polen – Breslau": (34, 23),
        "Polen – Warschau": (40, 27),
        "Polen – im Übrigen": (34, 23),
        "Portugal": (32, 21),
        "Ruanda": (44, 29),
        "Rumänien – Bukarest": (32, 21),
        "Rumänien – im Übrigen": (27, 18),
        "Russische Föderation – Moskau": (30, 20),
        "Russische Föderation – St. Petersburg": (28, 19),
        "Russische Föderation – im Übrigen": (28, 19),
        "Sambia": (38, 25),
        "Samoa": (39, 26),
        "San Marino": (34, 23),
        "Saudi-Arabien – Djidda": (57, 38),
        "Saudi-Arabien – Riad": (56, 37),
        "Saudi-Arabien – im Übrigen": (56, 37),
        "Schweden": (66, 44),
        "Schweiz – Genf": (66, 44),
        "Schweiz – im Übrigen": (64, 43),
        "Senegal": (42, 28),
        "Serbien": (27, 18),
        "Sierra Leone": (57, 38),
        "Simbabwe": (63, 42),
        "Singapur": (71, 48),
        "Slowakische Republik": (33, 22),
        "Slowenien": (38, 25),
        "Spanien – Barcelona": (34, 23),
        "Spanien – Kanarische Inseln": (36, 24),
        "Spanien – Madrid": (42, 28),
        "Spanien – Palma de Mallorca": (44, 29),
        "Spanien – im Übrigen": (34, 23),
        "Sri Lanka": (36, 24),
        "Sudan": (33, 22),
        "Syrien": (38, 25),
        "Südafrika – Johannesburg": (36, 24),
        "Südafrika – Kapstadt": (33, 22),
        "Südafrika – im Übrigen": (29, 20),
        "Südsudan": (51, 34),
        "Tadschikistan": (27, 18),
        "Taiwan": (51, 34),
        "Tansania": (44, 29),
        "Thailand": (36, 24),
        "Togo": (39, 26),
        "Tonga": (29, 20),
        "Trinidad und Tobago": (66, 44),
        "Tschad": (42, 28),
        "Tschechische Republik": (32, 21),
        "Tunesien": (40, 27),
        "Turkmenistan": (28, 19),
        "Türkei – Ankara": (32, 21),
        "Türkei – Izmir": (44, 29),
        "Türkei – im Übrigen": (24, 16),
        "Uganda": (41, 28),
        "Ukraine": (26, 17),
        "Ungarn": (32, 21),
        "Uruguay": (40, 27),
        "Usbekistan": (34, 23),
        "Vatikanstaat": (48, 32),
        "Venezuela": (45, 30),
        "Vereinigte Arabische Emirate": (65, 44),
        "Vereinigte Staaten von Amerika (USA) – Atlanta": (77, 52),
        "Vereinigte Staaten von Amerika (USA) – Boston": (63, 42),
        "Vereinigte Staaten von Amerika (USA) – Chicago": (65, 44),
        "Vereinigte Staaten von Amerika (USA) – Houston": (62, 41),
        "Vereinigte Staaten von Amerika (USA) – Los Angeles": (64, 43),
        "Vereinigte Staaten von Amerika (USA) – Miami": (65, 44),
        "Vereinigte Staaten von Amerika (USA) – New York City": (66, 44),
        "Vereinigte Staaten von Amerika (USA) – San Francisco": (59, 40),
        "Vereinigte Staaten von Amerika (USA) – Washington, D. C.": (66, 44),
        "Vereinigte Staaten von Amerika (USA) – im Übrigen": (59, 40),
        "Vietnam": (36, 24),
        "Weißrussland": (20, 13),
        "Zentralafrikanische Republik": (53, 36),
        "Zypern": (42, 28),
        "Ägypten": (50, 33),
        "Äquatorialguinea": (42, 28),
        "Äthiopien": (44, 29),
        "Österreich": (50, 33),
    },
    2026: {
        "Albanien": (33, 22),
        "Algerien": (47, 32),
        "Andorra": (45, 30),
        "Angola": (40, 27),
        "Argentinien": (42, 28),
        "Armenien": (29, 20),
        "Aserbaidschan": (44, 29),
        "Australien – Canberra": (74, 49),
        "Australien – Sydney": (57, 38),
        "Australien – im Übrigen": (57, 38),
        "Bahrain": (48, 32),
        "Bangladesch": (46, 31),
        "Barbados": (54, 36),
        "Belgien": (59, 40),
        "Benin": (40, 27),
        "Bhutan": (27, 18),
        "Bolivien": (46, 31),
        "Bosnien und Herzegowina": (32, 21),
        "Botsuana": (40, 27),
        "Brasilien – Brasilia": (51, 34),
        "Brasilien – Rio de Janeiro": (69, 46),
        "Brasilien – Sao Paulo": (46, 31),
        "Brasilien – im Übrigen": (46, 31),
        "Brunei": (45, 30),
        "Bulgarien": (38, 25),
        "Burkina Faso": (39, 26),
        "Burundi": (58, 39),
        "Chile": (44, 29),
        "China – Hongkong": (83, 56),
        "China – Peking": (57, 38),
        "China – Shanghai": (48, 32),
        "China – im Übrigen": (48, 32),
        "Costa Rica": (60, 40),
        "Dominikanische Republik": (50, 33),
        "Dschibuti": (77, 52),
        "Dänemark": (75, 50),
        "Ecuador": (27, 18),
        "El Salvador": (65, 44),
        "Eritrea": (46, 31),
        "Estland": (39, 26),
        "Fidschi": (32, 21),
        "Finnland": (54, 36),
        "Frankreich – Paris": (58, 39),
        "Frankreich – im Übrigen": (53, 36),
        "Gabun": (64, 43),
        "Gambia": (40, 27),
        "Georgien": (45, 30),
        "Ghana": (46, 31),
        "Griechenland – Athen": (40, 27),
        "Griechenland – im Übrigen": (36, 24),
        "Großbritannien und Nordirland – London": (66, 44),
        "Großbritannien und Nordirland – im Übrigen": (52, 35),
        "Guatemala": (46, 31),
        "Guinea": (59, 40),
        "Guinea-Bissau": (32, 21),
        "Honduras": (57, 38),
        "Indien – Bangalore": (42, 28),
        "Indien – Chennai": (22, 15),
        "Indien – Kalkutta": (32, 21),
        "Indien – Mumbai": (53, 36),
        "Indien – Neu Delhi": (46, 31),
        "Indien – im Übrigen": (22, 15),
        "Indonesien": (45, 30),
        "Iran": (33, 22),
        "Irland": (64, 43),
        "Island": (62, 41),
        "Israel": (59, 40),
        "Italien – Mailand": (42, 28),
        "Italien – Rom": (48, 32),
        "Italien – im Übrigen": (42, 28),
        "Jamaika": (39, 26),
        "Japan – Osaka": (33, 22),
        "Japan – Tokio": (50, 33),
        "Japan – im Übrigen": (33, 22),
        "Jordanien": (57, 38),
        "Kambodscha": (42, 28),
        "Kamerun": (56, 37),
        "Kanada – Ottawa": (62, 41),
        "Kanada – Toronto": (54, 36),
        "Kanada – Vancouver": (63, 42),
        "Kanada – im Übrigen": (54, 36),
        "Kap Verde": (38, 25),
        "Kasachstan": (33, 22),
        "Katar": (81, 54),
        "Kenia": (48, 32),
        "Kirgisistan": (35, 24),
        "Kolumbien": (34, 23),
        "Kongo, Demokratische Republik": (65, 44),
        "Kongo, Republik": (53, 36),
        "Korea, Republik": (39, 26),
        "Kosovo": (24, 16),
        "Kroatien": (46, 31),
        "Kuba": (51, 34),
        "Kuwait": (63, 42),
        "Laos": (35, 24),
        "Lesotho": (28, 19),
        "Lettland": (46, 31),
        "Libanon": (69, 46),
        "Liberia": (65, 44),
        "Liechtenstein": (57, 38),
        "Litauen": (48, 32),
        "Luxemburg": (63, 42),
        "Madagaskar": (33, 22),
        "Malawi": (41, 28),
        "Malaysia": (36, 24),
        "Malediven": (70, 47),
        "Mali": (42, 28),
        "Malta": (59, 40),
        "Marokko": (41, 28),
        "Marshall Inseln": (45, 30),
        "Mauretanien": (35, 24),
        "Mauritius": (44, 29),
        "Mexiko": (40, 27),
        "Moldau, Republik": (26, 17),
        "Monaco": (52, 35),
        "Mongolei": (23, 16),
        "Montenegro": (32, 21),
        "Mosambik": (51, 34),
        "Myanmar": (23, 16),
        "Namibia": (28, 19),
        "Nepal": (33, 22),
        "Neuseeland": (58, 39),
        "Nicaragua": (46, 31),
        "Niederlande": (58, 39),
        "Niger": (42, 28),
        "Nigeria": (52, 35),
        "Nordmazedonien": (27, 18),
        "Norwegen": (75, 50),
        "Oman": (64, 43),
        "Pakistan": (41, 28),
        "Palau": (51, 34),
        "Panama": (41, 28),
        "Papua-Neuguinea": (59, 40),
        "Paraguay": (39, 26),
        "Peru": (52, 35),
        "Philippinen": (41, 28),
        "Polen – Breslau": (34, 23),
        "Polen – Warschau": (40, 27),
        "Polen – im Übrigen": (34, 23),
        "Portugal": (32, 21),
        "Ruanda": (44, 29),
        "Rumänien": (38, 25),
        "Russische Föderation – Moskau": (30, 20),
        "Russische Föderation – St. Petersburg": (28, 19),
        "Russische Föderation – im Übrigen": (28, 19),
        "Sambia": (38, 25),
        "Samoa": (39, 26),
        "San Marino": (34, 23),
        "Saudi-Arabien – Djidda": (57, 38),
        "Saudi-Arabien – Riad": (56, 37),
        "Saudi-Arabien – im Übrigen": (56, 37),
        "Schweden": (66, 44),
        "Schweiz – Bern": (82, 55),
        "Schweiz – Genf": (70, 47),
        "Schweiz – im Übrigen": (70, 47),
        "Senegal": (48, 32),
        "Serbien": (27, 18),
        "Sierra Leone": (57, 38),
        "Simbabwe": (63, 42),
        "Singapur": (71, 48),
        "Slowakische Republik": (33, 22),
        "Slowenien": (38, 25),
        "Spanien – Barcelona": (34, 23),
        "Spanien – Kanarische Inseln": (36, 24),
        "Spanien – Madrid": (42, 28),
        "Spanien – Palma de Mallorca": (44, 29),
        "Spanien – im Übrigen": (34, 23),
        "Sri Lanka": (36, 24),
        "Südafrika – Johannesburg": (36, 24),
        "Südafrika – Kapstadt": (33, 22),
        "Südafrika – im Übrigen": (29, 20),
        "Südsudan": (51, 34),
        "Tadschikistan": (27, 18),
        "Taiwan": (51, 34),
        "Tansania": (44, 29),
        "Thailand": (36, 24),
        "Togo": (36, 24),
        "Tonga": (29, 20),
        "Trinidad und Tobago": (66, 44),
        "Tschad": (42, 28),
        "Tschechische Republik": (32, 21),
        "Tunesien": (40, 27),
        "Turkmenistan": (28, 19),
        "Türkei – Ankara": (32, 21),
        "Türkei – Izmir": (44, 29),
        "Türkei – im Übrigen": (24, 16),
        "Uganda": (45, 30),
        "Ukraine": (33, 22),
        "Ungarn": (32, 21),
        "Uruguay": (40, 27),
        "Usbekistan": (32, 21),
        "Vatikanstaat": (48, 32),
        "Venezuela": (51, 34),
        "Vereinigte Arabische Emirate": (81, 54),
        "Vereinigte Staaten von Amerika (USA) – Atlanta": (77, 52),
        "Vereinigte Staaten von Amerika (USA) – Boston": (63, 42),
        "Vereinigte Staaten von Amerika (USA) – Chicago": (65, 44),
        "Vereinigte Staaten von Amerika (USA) – Houston": (62, 41),
        "Vereinigte Staaten von Amerika (USA) – Los Angeles": (64, 43),
        "Vereinigte Staaten von Amerika (USA) – Miami": (65, 44),
        "Vereinigte Staaten von Amerika (USA) – New York City": (66, 44),
        "Vereinigte Staaten von Amerika (USA) – San Francisco": (59, 40),
        "Vereinigte Staaten von Amerika (USA) – Washington, D. C.": (66, 44),
        "Vereinigte Staaten von Amerika (USA) – im Übrigen": (59, 40),
        "Vietnam": (36, 24),
        "Weißrussland": (21, 14),
        "Zentralafrikanische Republik": (53, 36),
        "Zypern": (42, 28),
        "Ägypten": (50, 33),
        "Äquatorialguinea": (42, 28),
        "Äthiopien": (44, 29),
        "Österreich": (50, 33),
    },
}

IATA_TO_BMF = {
    "AAL": "Dänemark",
    "ABJ": "Côte d’Ivoire",
    "ABQ": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "ABV": "Nigeria",
    "ACC": "Ghana",
    "ACE": "Spanien – Kanarische Inseln",
    "ADB": "Türkei – Izmir",
    "ADD": "Äthiopien",
    "ADE": "Jemen",
    "ADL": "Australien – im Übrigen",
    "AEP": "Argentinien",
    "AGA": "Marokko",
    "AGP": "Spanien – im Übrigen",
    "AKL": "Neuseeland",
    "ALA": "Kasachstan",
    "ALC": "Spanien – im Übrigen",
    "ALG": "Algerien",
    "ALP": "Syrien",
    "AMD": "Indien – im Übrigen",
    "AMM": "Jordanien",
    "AMS": "Niederlande",
    "ANC": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "ANR": "Belgien",
    "AQJ": "Jordanien",
    "ARN": "Schweden",
    "ASB": "Turkmenistan",
    "ASU": "Paraguay",
    "ASW": "Ägypten",
    "ATH": "Griechenland – Athen",
    "ATL": "Vereinigte Staaten von Amerika (USA) – Atlanta",
    "AUA": "Aruba",
    "AUH": "Vereinigte Arabische Emirate",
    "AUS": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "AYT": "Türkei – im Übrigen",
    "BAG": "Irak",
    "BAH": "Bahrain",
    "BCN": "Spanien – Barcelona",
    "BEG": "Serbien",
    "BEN": "Libyen",
    "BER": "Deutschland",
    "BEY": "Libanon",
    "BFS": "Großbritannien und Nordirland – im Übrigen",
    "BGI": "Barbados",
    "BGO": "Norwegen",
    "BGY": "Italien – Mailand",
    "BHX": "Großbritannien und Nordirland – im Übrigen",
    "BIO": "Spanien – im Übrigen",
    "BIQ": "Frankreich – im Übrigen",
    "BIS": "Kirgisistan",
    "BJL": "Gambia",
    "BJM": "Burundi",
    "BJV": "Türkei – im Übrigen",
    "BKI": "Malaysia",
    "BKK": "Thailand",
    "BKO": "Mali",
    "BLL": "Dänemark",
    "BLQ": "Italien – im Übrigen",
    "BLR": "Indien – Bangalore",
    "BMA": "Schweden",
    "BNA": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "BNE": "Australien – im Übrigen",
    "BNX": "Bosnien und Herzegowina",
    "BOD": "Frankreich – im Übrigen",
    "BOG": "Kolumbien",
    "BOJ": "Bulgarien",
    "BOM": "Indien – Mumbai",
    "BOS": "Vereinigte Staaten von Amerika (USA) – Boston",
    "BRE": "Deutschland",
    "BRI": "Italien – im Übrigen",
    "BRN": "Schweiz – im Übrigen",
    "BRQ": "Tschechische Republik",
    "BRU": "Belgien",
    "BSB": "Brasilien – Brasilia",
    "BSL": "Schweiz – im Übrigen",
    "BSR": "Irak",
    "BTS": "Slowakei",
    "BUD": "Ungarn",
    "BUF": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "BUH": "Rumänien – Bukarest",
    "BUQ": "Simbabwe",
    "BUR": "Vereinigte Staaten von Amerika (USA) – Los Angeles",
    "BUS": "Georgien",
    "BVA": "Frankreich – Paris",
    "BWI": "Vereinigte Staaten von Amerika (USA) – Washington, D. C.",
    "BZE": "Belize",
    "BZV": "Kongo, Republik",
    "CAG": "Italien – im Übrigen",
    "CAI": "Ägypten",
    "CAN": "China – Kanton",
    "CBR": "Australien – Canberra",
    "CCS": "Venezuela",
    "CCU": "Indien – Kalkutta",
    "CDG": "Frankreich – Paris",
    "CEB": "Philippinen",
    "CGH": "Brasilien – Sao Paulo",
    "CGK": "Indonesien",
    "CGN": "Deutschland",
    "CGP": "Bangladesch",
    "CHC": "Neuseeland",
    "CIA": "Italien – Rom",
    "CJU": "Korea, Republik",
    "CKG": "China – im Übrigen",
    "CKY": "Guinea",
    "CLE": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "CLJ": "Rumänien – im Übrigen",
    "CLT": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "CMB": "Sri Lanka",
    "CMH": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "CMN": "Marokko",
    "CNS": "Australien – im Übrigen",
    "CNX": "Thailand",
    "COK": "Indien – im Übrigen",
    "COO": "Benin",
    "COR": "Argentinien",
    "CPH": "Dänemark",
    "CPT": "Südafrika – Kapstadt",
    "CRL": "Belgien",
    "CTA": "Italien – im Übrigen",
    "CTG": "Kolumbien",
    "CTS": "Japan – im Übrigen",
    "CTU": "China – Chengdu",
    "CUN": "Mexiko",
    "CUR": "Curaçao",
    "CUZ": "Peru",
    "CWB": "Brasilien – im Übrigen",
    "CZL": "Algerien",
    "CZM": "Mexiko",
    "DAC": "Bangladesch",
    "DAD": "Vietnam",
    "DAM": "Syrien",
    "DAR": "Tansania",
    "DBV": "Kroatien",
    "DCA": "Vereinigte Staaten von Amerika (USA) – Washington, D. C.",
    "DEB": "Ungarn",
    "DEL": "Indien – Neu Delhi",
    "DEN": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "DFW": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "DJE": "Tunesien",
    "DKR": "Senegal",
    "DLA": "Kamerun",
    "DLC": "China – im Übrigen",
    "DME": "Russische Föderation – Moskau",
    "DMK": "Thailand",
    "DMM": "Saudi-Arabien – im Übrigen",
    "DOH": "Katar",
    "DPS": "Indonesien",
    "DRS": "Deutschland",
    "DTW": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "DUB": "Irland",
    "DUR": "Südafrika – im Übrigen",
    "DUS": "Deutschland",
    "DVO": "Philippinen",
    "DWC": "Vereinigte Arabische Emirate",
    "DXB": "Vereinigte Arabische Emirate",
    "DYU": "Tadschikistan",
    "EBB": "Uganda",
    "EBL": "Irak",
    "EDI": "Großbritannien und Nordirland – im Übrigen",
    "EMA": "Großbritannien und Nordirland – im Übrigen",
    "ERF": "Deutschland",
    "ESB": "Türkei – Ankara",
    "ETM": "Israel",
    "EVN": "Armenien",
    "EWR": "Vereinigte Staaten von Amerika (USA) – New York City",
    "EZE": "Argentinien",
    "FAO": "Portugal",
    "FCO": "Italien – Rom",
    "FDH": "Deutschland",
    "FIH": "Kongo, Demokratische Republik",
    "FKB": "Deutschland",
    "FLL": "Vereinigte Staaten von Amerika (USA) – Miami",
    "FMO": "Deutschland",
    "FNA": "Sierra Leone",
    "FOR": "Brasilien – im Übrigen",
    "FRA": "Deutschland",
    "FRU": "Kirgisistan",
    "FUE": "Spanien – Kanarische Inseln",
    "FUK": "Japan – im Übrigen",
    "GBE": "Botsuana",
    "GDL": "Mexiko",
    "GDN": "Polen – im Übrigen",
    "GIG": "Brasilien – Rio de Janeiro",
    "GLA": "Großbritannien und Nordirland – im Übrigen",
    "GMP": "Korea, Republik",
    "GOA": "Italien – im Übrigen",
    "GOI": "Indien – im Übrigen",
    "GOT": "Schweden",
    "GRU": "Brasilien – Sao Paulo",
    "GRZ": "Österreich",
    "GUA": "Guatemala",
    "GVA": "Schweiz – Genf",
    "GYD": "Aserbaidschan",
    "GYE": "Ecuador",
    "HAJ": "Deutschland",
    "HAM": "Deutschland",
    "HAN": "Vietnam",
    "HAV": "Kuba",
    "HBA": "Australien – im Übrigen",
    "HEL": "Finnland",
    "HHN": "Deutschland",
    "HKG": "China – Hongkong",
    "HKT": "Thailand",
    "HND": "Japan – Tokio",
    "HNL": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "HOG": "Kuba",
    "HOU": "Vereinigte Staaten von Amerika (USA) – Houston",
    "HRE": "Simbabwe",
    "HRG": "Ägypten",
    "HYD": "Indien – im Übrigen",
    "IAD": "Vereinigte Staaten von Amerika (USA) – Washington, D. C.",
    "IAH": "Vereinigte Staaten von Amerika (USA) – Houston",
    "IBZ": "Spanien – im Übrigen",
    "ICN": "Korea, Republik",
    "IEV": "Ukraine",
    "IKA": "Iran",
    "IND": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "INI": "Serbien",
    "INN": "Österreich",
    "IPC": "Chile",
    "ISB": "Pakistan",
    "IST": "Türkei – im Übrigen",
    "ITM": "Japan – Osaka",
    "JAI": "Indien – im Übrigen",
    "JAX": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "JED": "Saudi-Arabien – Djidda",
    "JFK": "Vereinigte Staaten von Amerika (USA) – New York City",
    "JIB": "Dschibuti",
    "JNB": "Südafrika – Johannesburg",
    "JOG": "Indonesien",
    "JRO": "Tansania",
    "KAN": "Nigeria",
    "KBP": "Ukraine",
    "KBV": "Thailand",
    "KCH": "Malaysia",
    "KEF": "Island",
    "KGL": "Ruanda",
    "KHH": "Taiwan",
    "KHI": "Pakistan",
    "KIN": "Jamaika",
    "KIV": "Moldau, Republik",
    "KIX": "Japan – Osaka",
    "KLU": "Österreich",
    "KMG": "China – im Übrigen",
    "KMS": "Ghana",
    "KOA": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "KRK": "Polen – im Übrigen",
    "KRT": "Sudan",
    "KSC": "Slowakei",
    "KTM": "Nepal",
    "KUL": "Malaysia",
    "KUN": "Litauen",
    "KUT": "Georgien",
    "KWI": "Kuwait",
    "LAD": "Angola",
    "LAS": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "LAX": "Vereinigte Staaten von Amerika (USA) – Los Angeles",
    "LBA": "Großbritannien und Nordirland – im Übrigen",
    "LBC": "Deutschland",
    "LBV": "Gabun",
    "LCA": "Zypern",
    "LCY": "Großbritannien und Nordirland – London",
    "LED": "Russische Föderation – St. Petersburg",
    "LEJ": "Deutschland",
    "LFW": "Togo",
    "LGA": "Vereinigte Staaten von Amerika (USA) – New York City",
    "LGB": "Vereinigte Staaten von Amerika (USA) – Los Angeles",
    "LGW": "Großbritannien und Nordirland – London",
    "LHE": "Pakistan",
    "LHR": "Großbritannien und Nordirland – London",
    "LIM": "Peru",
    "LIN": "Italien – Mailand",
    "LIR": "Costa Rica",
    "LIS": "Portugal",
    "LJU": "Slowenien",
    "LNZ": "Österreich",
    "LON": "Großbritannien und Nordirland – London",
    "LOS": "Nigeria",
    "LPA": "Spanien – Kanarische Inseln",
    "LPB": "Bolivien",
    "LPQ": "Laos",
    "LTN": "Großbritannien und Nordirland – London",
    "LUG": "Schweiz – im Übrigen",
    "LUN": "Sambia",
    "LUX": "Luxemburg",
    "LWO": "Ukraine",
    "LXR": "Ägypten",
    "LYS": "Frankreich – im Übrigen",
    "MAA": "Indien – Chennai",
    "MAD": "Spanien – Madrid",
    "MAN": "Großbritannien und Nordirland – im Übrigen",
    "MAO": "Brasilien – im Übrigen",
    "MAR": "Venezuela",
    "MBA": "Kenia",
    "MBJ": "Jamaika",
    "MCI": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "MCO": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "MCT": "Oman",
    "MDE": "Kolumbien",
    "MDL": "Myanmar",
    "MDW": "Vereinigte Staaten von Amerika (USA) – Chicago",
    "MED": "Saudi-Arabien – im Übrigen",
    "MEL": "Australien – im Übrigen",
    "MEM": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "MES": "Indonesien",
    "MEX": "Mexiko",
    "MGA": "Nicaragua",
    "MGQ": "Somalia",
    "MHD": "Iran",
    "MHG": "Deutschland",
    "MIA": "Vereinigte Staaten von Amerika (USA) – Miami",
    "MIL": "Italien – Mailand",
    "MLA": "Malta",
    "MMX": "Schweden",
    "MNL": "Philippinen",
    "MPL": "Frankreich – im Übrigen",
    "MPM": "Mosambik",
    "MRS": "Frankreich – im Übrigen",
    "MRU": "Mauritius",
    "MSP": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "MSQ": "Belarus",
    "MTY": "Mexiko",
    "MUC": "Deutschland",
    "MVD": "Uruguay",
    "MXP": "Italien – Mailand",
    "NAN": "Fidschi",
    "NAP": "Italien – im Übrigen",
    "NAS": "Bahamas",
    "NBO": "Kenia",
    "NCE": "Frankreich – im Übrigen",
    "NCL": "Großbritannien und Nordirland – im Übrigen",
    "NDJ": "Tschad",
    "NGO": "Japan – im Übrigen",
    "NIM": "Niger",
    "NKC": "Mauretanien",
    "NKG": "China – im Übrigen",
    "NOC": "Irland",
    "NOU": "Neukaledonien",
    "NRN": "Deutschland",
    "NRT": "Japan – Tokio",
    "NSI": "Kamerun",
    "NTE": "Frankreich – im Übrigen",
    "NUE": "Deutschland",
    "NUR": "Kasachstan",
    "NYC": "Vereinigte Staaten von Amerika (USA) – New York City",
    "NYO": "Schweden",
    "OAK": "Vereinigte Staaten von Amerika (USA) – San Francisco",
    "ODS": "Ukraine",
    "OGG": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "OKA": "Japan – im Übrigen",
    "OKC": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "OMA": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "ONT": "Vereinigte Staaten von Amerika (USA) – Los Angeles",
    "OOL": "Australien – im Übrigen",
    "OPO": "Portugal",
    "ORD": "Vereinigte Staaten von Amerika (USA) – Chicago",
    "ORK": "Irland",
    "ORN": "Algerien",
    "ORY": "Frankreich – Paris",
    "OSL": "Norwegen",
    "OTP": "Rumänien – Bukarest",
    "OUA": "Burkina Faso",
    "OUD": "Marokko",
    "OUL": "Finnland",
    "OXB": "Guinea-Bissau",
    "PAD": "Deutschland",
    "PBI": "Vereinigte Staaten von Amerika (USA) – Miami",
    "PDX": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "PEK": "China – Peking",
    "PEN": "Malaysia",
    "PER": "Australien – im Übrigen",
    "PFO": "Zypern",
    "PHL": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "PHX": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "PIT": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "PKX": "China – Peking",
    "PLZ": "Südafrika – im Übrigen",
    "PMI": "Spanien – Palma de Mallorca",
    "PMO": "Italien – im Übrigen",
    "PNH": "Kambodscha",
    "PNQ": "Indien – im Übrigen",
    "PNR": "Kongo, Republik",
    "POA": "Brasilien – im Übrigen",
    "POS": "Trinidad und Tobago",
    "POZ": "Polen – im Übrigen",
    "PPT": "Französisch-Polynesien",
    "PRG": "Tschechische Republik",
    "PRN": "Kosovo",
    "PSA": "Italien – im Übrigen",
    "PTY": "Panama",
    "PUJ": "Dominikanische Republik",
    "PUS": "Korea, Republik",
    "PUY": "Kroatien",
    "PVG": "China – Shanghai",
    "PVR": "Mexiko",
    "RAK": "Marokko",
    "RDU": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "REC": "Brasilien – im Übrigen",
    "REP": "Kambodscha",
    "RGN": "Myanmar",
    "RIX": "Lettland",
    "RKV": "Island",
    "ROB": "Liberia",
    "ROC": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "RUH": "Saudi-Arabien – Riad",
    "SAH": "Jemen",
    "SAL": "El Salvador",
    "SAN": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "SAO": "Brasilien – Sao Paulo",
    "SAT": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "SAW": "Türkei – im Übrigen",
    "SCL": "Chile",
    "SCN": "Deutschland",
    "SDQ": "Dominikanische Republik",
    "SDU": "Brasilien – Rio de Janeiro",
    "SEA": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "SEL": "Korea, Republik",
    "SEN": "Großbritannien und Nordirland – London",
    "SEZ": "Seychellen",
    "SFA": "Tunesien",
    "SFO": "Vereinigte Staaten von Amerika (USA) – San Francisco",
    "SGN": "Vietnam",
    "SHA": "China – Shanghai",
    "SHJ": "Vereinigte Arabische Emirate",
    "SIN": "Singapur",
    "SJC": "Vereinigte Staaten von Amerika (USA) – San Francisco",
    "SJD": "Mexiko",
    "SJJ": "Bosnien und Herzegowina",
    "SJO": "Costa Rica",
    "SKD": "Usbekistan",
    "SKG": "Griechenland – im Übrigen",
    "SKP": "Nordmazedonien",
    "SLC": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "SLL": "Oman",
    "SNA": "Vereinigte Staaten von Amerika (USA) – Los Angeles",
    "SNN": "Irland",
    "SOF": "Bulgarien",
    "SPC": "Spanien – Kanarische Inseln",
    "SPU": "Kroatien",
    "SRG": "Indonesien",
    "SSA": "Brasilien – im Übrigen",
    "SSG": "Äquatorialguinea",
    "SSH": "Ägypten",
    "STI": "Dominikanische Republik",
    "STL": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "STN": "Großbritannien und Nordirland – London",
    "STR": "Deutschland",
    "SUB": "Indonesien",
    "SUV": "Fidschi",
    "SVG": "Norwegen",
    "SVO": "Russische Föderation – Moskau",
    "SVQ": "Spanien – im Übrigen",
    "SXF": "Deutschland",
    "SYD": "Australien – Sydney",
    "SZG": "Österreich",
    "SZX": "China – im Übrigen",
    "TAO": "China – im Übrigen",
    "TAS": "Usbekistan",
    "TBS": "Georgien",
    "TFN": "Spanien – Kanarische Inseln",
    "TFS": "Spanien – Kanarische Inseln",
    "TGD": "Montenegro",
    "TGU": "Honduras",
    "THR": "Iran",
    "TIA": "Albanien",
    "TIP": "Libyen",
    "TIV": "Montenegro",
    "TKU": "Finnland",
    "TLL": "Estland",
    "TLS": "Frankreich – im Übrigen",
    "TLV": "Israel",
    "TML": "Ghana",
    "TMP": "Finnland",
    "TNG": "Marokko",
    "TNR": "Madagaskar",
    "TOS": "Norwegen",
    "TPA": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "TPE": "Taiwan",
    "TRD": "Norwegen",
    "TRN": "Italien – im Übrigen",
    "TSE": "Kasachstan",
    "TSN": "China – im Übrigen",
    "TSR": "Rumänien – im Übrigen",
    "TUL": "Vereinigte Staaten von Amerika (USA) – im Übrigen",
    "TUN": "Tunesien",
    "TXL": "Deutschland",
    "TYO": "Japan – Tokio",
    "TZX": "Türkei – im Übrigen",
    "UIO": "Ecuador",
    "ULN": "Mongolei",
    "USM": "Thailand",
    "VAR": "Bulgarien",
    "VCE": "Italien – im Übrigen",
    "VDA": "Israel",
    "VIE": "Österreich",
    "VKO": "Russische Föderation – Moskau",
    "VLC": "Spanien – im Übrigen",
    "VNO": "Litauen",
    "VPY": "Mosambik",
    "VRA": "Kuba",
    "VTE": "Laos",
    "VVI": "Bolivien",
    "WAS": "Vereinigte Staaten von Amerika (USA) – Washington, D. C.",
    "WAW": "Polen – Warschau",
    "WDH": "Namibia",
    "WLG": "Neuseeland",
    "WMI": "Polen – Warschau",
    "WRO": "Polen – Breslau",
    "WUH": "China – im Übrigen",
    "XIY": "China – im Übrigen",
    "XMN": "China – im Übrigen",
    "YEG": "Kanada – im Übrigen",
    "YHZ": "Kanada – im Übrigen",
    "YOW": "Kanada – Ottawa",
    "YQB": "Kanada – im Übrigen",
    "YQM": "Kanada – im Übrigen",
    "YQR": "Kanada – im Übrigen",
    "YUL": "Kanada – im Übrigen",
    "YVR": "Kanada – Vancouver",
    "YWG": "Kanada – im Übrigen",
    "YYC": "Kanada – im Übrigen",
    "YYZ": "Kanada – Toronto",
    "ZAD": "Kroatien",
    "ZAG": "Kroatien",
    "ZNZ": "Tansania",
    "ZQN": "Neuseeland",
    "ZRH": "Schweiz – im Übrigen",
}
