-- Runtime-extensible airline onboarding. URLs are encrypted by the backend;
-- raw roster PDFs remain in the private ax_logbook_upload inbox.
create table if not exists public.airline_support_requests (
    id bigint generated by default as identity primary key,
    token text not null,
    airline_name text not null,
    normalized_name text not null,
    homebase text,
    source_kind text not null,
    source_upload_id bigint references public.ax_logbook_upload(id) on delete set null,
    source_filename text,
    source_url_enc text,
    source_fingerprint text not null,
    status text not null default 'pending',
    import_source text,
    events_count integer,
    attempt_count integer not null default 0,
    last_error text,
    next_attempt_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    completed_at timestamptz,
    constraint airline_support_source_kind_check check (source_kind in ('ical_url', 'pdf')),
    constraint airline_support_status_check check (status in ('pending', 'processing', 'supported', 'review', 'failed')),
    constraint airline_support_homebase_check check (homebase is null or homebase ~ '^[A-Z]{3}$')
);
create index if not exists idx_airline_support_requests_pending
    on public.airline_support_requests (status, next_attempt_at, id)
    where status in ('pending', 'processing');
create index if not exists idx_airline_support_requests_owner
    on public.airline_support_requests (token, id desc);

create table if not exists public.airline_catalog (
    normalized_name text primary key,
    display_name text not null,
    status text not null default 'supported',
    source_kind text,
    last_verified_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint airline_catalog_status_check check (status in ('supported', 'review', 'disabled')),
    constraint airline_catalog_source_kind_check check (source_kind is null or source_kind in ('ical_url', 'pdf'))
);
alter table public.airline_support_requests enable row level security;
alter table public.airline_catalog enable row level security;
revoke all on public.airline_support_requests from anon, authenticated;
revoke all on public.airline_catalog from anon, authenticated;
